class VLMImgGenerator:
    def __init__(self):
        # Configure the image generation module
        self.model_name = None
        self.memory_img_h, self.memory_img_w = None, None
        self.memory_patch_h, self.memory_patch_w = None, None

        # Initialize the memory image
        self._init_memory_img()

    def _init_memory_img(self):
        """
        Initialize the memory image which is grid of patches
        Each patch i is an image generated by the VLM to represent the agent's i-th step
        """
        self.memory_img = None

    def _set_instruction_prompt(self):
        self.instruction_prompt = "Put instruction prompt here"

    def generate_img(self, step_num: int, intent: str, dom_tree: str, cot: str, action: str):
        """
        Generate the image for the given step.
        """
        # TODO:
        # 1. Generate a memory patch using Gemini API
        # 2. Update the memory image with the new patch
        # 3. Return the memory image
        return self.memory_img

    def _generate_memory_patch(self):
        """Generate a memory patch using Gemini API and align it within patch size"""
        pass

    def _update_memory_img(self, i, patch):
        """Update the memory image with the new patch"""
        pass